export const techIcons: Record<string, string> = {
  'Linux': 'uil:linux',
  'Docker': 'mdi:docker',
  'Caddy': 'file-icons:caddy',
  'Authentik': 'simple-icons:authentik',
  'Grafana': 'devicon-plain:grafana',
  'Home Assistant': 'simple-icons:homeassistant',
  'Git': 'simple-icons:git',
  'React': 'simple-icons:react',
  'Vue': 'teenyicons:vue-solid',
  'Flutter': 'simple-icons:flutter',
  'Typescript': 'simple-icons:typescript',
  'Dart': 'simple-icons:dart',
  'Rust': 'simple-icons:rust',
  'Tailwind': 'simple-icons:tailwindcss',
  'Nuxt': 'simple-icons:nuxt',
  'Markdown': 'simple-icons:markdown',
  'Vite': 'simple-icons:vite',
  'SQL': 'mage:database',
  'GitHub Actions': 'devicon-plain:githubactions',
  'LLM': 'simple-icons:openai',
  'Firebase': 'simple-icons:firebase',
  'Node.js': 'simple-icons:nodedotjs',
  'Deno': 'simple-icons:deno',
  'Python': 'simple-icons:python',
  'PostgreSQL': 'simple-icons:postgresql',
  'MongoDB': 'simple-icons:mongodb',
  'REST': 'mdi:api',
  'GraphQL': 'simple-icons:graphql',
  'Java': 'devicon-plain:java',
  'Gradle': 'simple-icons:gradle',
  'Niri': 'mdi:window-shutter',
  'Quickshell': 'mdi:console-line',
  'Qt Quick (QML)': 'simple-icons:qt',
  'Wayland': 'simple-icons:wayland',
  'Home Manager': 'mdi:home-cog',
  'Fish': 'mdi:fish',
  'direnv': 'mdi:folder-arrow-up-down',
};

export const getTechIcon = (name: string) => techIcons[name] || 'mage:box-3d';
