import { z } from "zod";
import { createSelectSchema, createInsertSchema } from "drizzle-zod";
import { blogPosts, blogPostTranslations } from "~~/server/db/schema";
import { dateSchema } from "./date.schema";
import { authorSchema } from "./author.schema";
import { categorySchema } from "./category.schema";
import { tagSchema } from "./tag.schema";

/**
 * @schema blogPostBaseSchema
 */
export const blogPostBaseSchema = createSelectSchema(blogPosts, {
  publishedAt: dateSchema,
  createdAt: dateSchema,
  updatedAt: dateSchema,
});

/**
 * @schema blogPostTranslationBaseSchema
 */
export const blogPostTranslationBaseSchema = createSelectSchema(
  blogPostTranslations,
  {
    updatedAt: dateSchema,
  },
);

/**
 * @schema blogPostCreateSchema
 */
export const blogPostCreateSchema = createInsertSchema(blogPosts, {
  publishedAt: dateSchema,
}).extend({
  translationKey: z.string().optional(), // Auto-generated by engine if not provided
  locale: z.string(),
  slug: z.string(),
  title: z.string(),
  body: z.string(),
  excerpt: z.string().optional().nullable(),
  categoryName: z.string().trim().optional().nullable(),
  tags: z.array(z.string().trim()).optional().default([]),
});

export const blogPostUpdateSchema = blogPostCreateSchema.partial();

// --- Relation Composition ---

const blogPostRelations = {
  category: categorySchema.nullable(),
  tags: z.array(z.object({ tag: tagSchema })),
  author: authorSchema.nullable(),
  translations: z.array(blogPostTranslationBaseSchema),
};

/**
 * @schema blogPostResponseSchema
 */
export const blogPostResponseSchema = blogPostBaseSchema
  .extend({
    title: z.string(),
    slug: z.string(),
    body: z.string(),
    excerpt: z.string().nullable(),
    readingTime: z.number().nullable(),
  })
  .extend({
    category: blogPostRelations.category,
    tags: blogPostRelations.tags,
    author: blogPostRelations.author,
  })
  .transform((val) => {
    return {
      ...val,
      tags: val.tags?.map((t) => t.tag) ?? [],
    };
  });

/**
 * @schema blogPostStudioResponseSchema
 */
export const blogPostStudioResponseSchema =
  blogPostBaseSchema.extend(blogPostRelations);

// --- Types ---

export type BlogPost = z.infer<typeof blogPostBaseSchema>;
export type BlogPostCreate = z.infer<typeof blogPostCreateSchema>;
export type BlogPostUpdate = z.infer<typeof blogPostUpdateSchema>;
export type BlogPostResponse = z.infer<typeof blogPostResponseSchema>;
export type BlogPostStudioResponse = z.infer<
  typeof blogPostStudioResponseSchema
>;
