import { z } from "zod";
import { createSelectSchema, createInsertSchema } from "drizzle-zod";
import { projects, projectTranslations } from "~~/server/db/schema";
import { dateSchema } from "./date.schema";
import { authorSchema } from "./author.schema";
import { categorySchema } from "./category.schema";
import { tagSchema } from "./tag.schema";
import { technologySchema } from "./technology.schema";

/**
 * @schema projectBaseSchema
 */
export const projectBaseSchema = createSelectSchema(projects, {
  publishedAt: dateSchema,
  createdAt: dateSchema,
  updatedAt: dateSchema,
});

/**
 * @schema projectTranslationBaseSchema
 */
export const projectTranslationBaseSchema = createSelectSchema(
  projectTranslations,
  {
    updatedAt: dateSchema,
  },
);

/**
 * @schema projectCreateSchema
 */
export const projectCreateSchema = createInsertSchema(projects, {
  publishedAt: dateSchema,
  createdAt: dateSchema,
  updatedAt: dateSchema,
}).extend({
  translationKey: z.string().optional(), // Auto-generated by engine if not provided
  locale: z.string(),
  slug: z.string(),
  title: z.string(),
  subtitle: z.string().optional().nullable(),
  body: z.string(),
  features: z.array(z.string()).optional().nullable(),
  learned: z.array(z.string()).optional().nullable(),
  challenges: z.array(z.string()).optional().nullable(),
  categoryName: z.string().trim().optional().nullable(),
  tags: z.array(z.string().trim()).optional().default([]),
  techstack: z.array(z.string().trim()).optional().default([]),
});

export const projectUpdateSchema = projectCreateSchema.partial();

// --- Relation Composition ---

const projectRelations = {
  category: categorySchema.nullable(),
  tags: z.array(z.object({ tag: tagSchema })),
  techstack: z.array(z.object({ technology: technologySchema })),
  author: authorSchema.nullable(),
  translations: z.array(projectTranslationBaseSchema),
};

/**
 * @schema projectResponseSchema
 */
export const projectResponseSchema = projectBaseSchema
  .extend({
    title: z.string(),
    slug: z.string(),
    subtitle: z.string().nullable(),
    body: z.string(),
    features: z.array(z.string()).nullable(),
    learned: z.array(z.string()).nullable(),
    challenges: z.array(z.string()).nullable(),
  })
  .extend({
    category: projectRelations.category,
    tags: projectRelations.tags,
    techstack: projectRelations.techstack,
    author: projectRelations.author,
  })
  .transform((val) => {
    return {
      ...val,
      tags: val.tags?.map((t) => t.tag) ?? [],
      techstack: val.techstack?.map((t) => t.technology) ?? [],
    };
  });

/**
 * @schema projectStudioResponseSchema
 */
export const projectStudioResponseSchema =
  projectBaseSchema.extend(projectRelations);

// --- Types ---

export type Project = z.infer<typeof projectBaseSchema>;
export type ProjectCreate = z.infer<typeof projectCreateSchema>;
export type ProjectUpdate = z.infer<typeof projectUpdateSchema>;
export type ProjectResponse = z.infer<typeof projectResponseSchema>;
export type ProjectStudioResponse = z.infer<typeof projectStudioResponseSchema>;
